package-lock.json
src/components/features/auth/LoginButton.tsx

💄 feat: create Login component

---

src/app/api/auth/[...nextauth]/route.ts

🐛 fix: resolve login issue

---

src/app/community/write/page.tsx
src/components/features/community/community-create/FeedImageUpload.tsx

💄 style: implement community post creation UI

---

src/app/user/myfeed/page.tsx

💄 style: complete UI for community myfeed page

---

src/app/user/myfeed/layout.tsx
src/components/features/community/community-bookmark/BookmarkFeedCard.tsx
src/components/features/community/community-detail/CommentInput.tsx
src/components/features/community/community-detail/CommentItem.tsx

✨ feat: implement UI and logic for comment, share, and bookmark in community feed

---

src/app/shop/cart/page.tsx

- Support individual/all selection, deletion
- Reflect price changes on quantity update
- 개별 상품 선택 / 해제 / 삭제 / 수량 증감 
- 전체 상품 선택 / 해제 / 삭제
- 선택 상품 가격 변동 기능 및 수량 변경에 따른 가격 변동 반영
resolves #56

✨ feat: Add product selection & dynamic pricing

---

src/app/api/comments/route.ts
src/components/features/community/community-detail/CommentInput.tsx
src/components/features/community/community-main/CommunityMain.tsx
src/components/features/community/community-main/CommunityMainHeader.tsx

🐛 fix: fix typos in multiple function names

---

middleware.ts
src/app/api/auth/[...nextauth]/route.ts
src/app/api/comments/route.ts
src/data/functions/CommentsFetch.ts
src/store/auth.store.ts

- 하드코딩된 OAuth 회원가입 URL을 .env로 분리하여 관리 
resolves #77

♻️ refactor: move OAuth signup URL to .env

---

api/bruno/1bone/회원/social Login.bru
api/bruno/1bone/회원/회원 조회.bru
src/app/api/auth/[...nextauth]/route.ts
src/components/features/auth/TokenSync.tsx
src/store/auth.store.ts

- 로그인 사용자 데이터 image, address, phone 추가
resolves #75

✨ feat: add image, phone, and address to user data

---

package-lock.json
src/app/api/auth/[...nextauth]/route.ts

🐛 fix: Add NEXTAUTH_SECRET for production auth

---

src/app/live/LiveOverlay.tsx
src/components/features/shop/ProductDetail/ProductDetailClient.tsx
src/store/live.store.ts

- type import 코드 수정
- live overlay component Goback 버튼 매개변수 제거
resolves #94

🚨 hotfix: resolve build error

---

src/app/shop/[productId]/page.tsx
src/components/features/shop/ProductDetail/OptionSelector.tsx
src/components/features/shop/ProductDetail/ProductDetail.tsx
src/components/features/shop/ProductDetail/ProductDetailClient.tsx
src/types/product.ts

- 연산 방식 변경 및 주석 수정
- 옵션 로직 및 할인 가격 계산에 대한 인라인 주석 추가
- extra.options 기반 옵션 드롭다운 자동 생성 및 라벨 동적 처리
- 옵션 string 대신 상품명 수량/금액 헤더에 표시, 옵션 없을 때 선택 UI 미노출
- cartActions 컴포넌트에 item prop 추가 및 관련 로직 반영
- productquantityselector에 item prop을 추가하고 옵션 표시 로직 개선
- options 추출 로직 추가 및 options prop 사용 방식 리팩터
resolves #27

♻️ refactor: improve dynamic UI and discount logic by option

---

src/components/features/shop/ShopCategory.tsx
src/components/features/shop/ShopLiveProducts.tsx

- 카테고리 스와이퍼 수정
- 라이브 종료 |  예정 구분 오버레이
resolves #117

✨ feat: shop live done

---

src/app/(auth)/login/page.tsx
src/components/features/auth/RecentLogin.tsx
src/components/features/auth/SocialLoginButtons.tsx
src/components/features/user/setting/LogoutButton.tsx
src/lib/signInHandler.ts

- [] 최근 로그인 계정 표시
resolves #121

✨ feat: add recent login account memory and display feature

---

src/app/shop/ShopList.tsx
src/components/features/shop/ShopLiveProducts.tsx
src/components/features/shop/ShopProduct.tsx

- 상품 경로 수정
- 라이브 예정, 종료 상품 제대로 막기 
resolves #128

🩹  fix products path & block before or after live products path

---

src/app/shop/cart/page.tsx
src/components/features/shop/ProductDetail/ProductDetail.tsx
src/components/features/shopping-cart/CartItemCard.tsx

- 장바구니 및 구매하기 버튼 색상 변경
- 단건 삭제 시 장바구니 id 변경 및 상태 업데이트 반영
- 장바구니 페이지 반응형으로 변경
resolves #56 #27

🐛 fix: improve cart button colors and responsiveness, and fix single item deletion state update

---

src/components/features/user/UserShopTab.tsx
src/data/functions/OrderFetch.ts
src/types/orders.ts

✨ feat: add shopping list to My Page

---

src/components/features/user/UserShopTab.tsx
src/components/features/user/alarm/RandomModal.tsx

- 오늘 하루 보지 않기 밑줄 없앰
- 이동 및 일시정지 버튼 제거
- 기존 버튼에서 스와이프로 변경
- 자동 슬라이드 3초에서 3.5초로 변경
resolves #171

♻️ refactor: add swipe gesture support to bottom sheet modal

---

src/app/search/page.tsx
src/app/search/searchList.tsx
src/app/shop/ShopList.tsx
src/components/common/SmallLoading.tsx
src/store/live.store.ts
src/utils/product.ts

- show true인 상품들만 렌더링되도록 수정
- loading 하단으로 
resolves #181

✨ feat render only show products & change loading ui

---

src/components/common/LogoutModal.tsx
src/components/features/user/setting/LogoutButton.tsx

✨ feat: implement logout confirmation modal

---

src/components/features/shop/ProductDetail/ProductDetailClient.tsx

- 결제 버튼 반응형 중단점 제거 및 최대 너비 지정, 누락된 선택삭제 버튼 추가로 UX 개선
- 상품 이미지 라운드 및 테두리, 수량 조절·삭제 버튼 색상·두께 조정
- 여러 상품 체크박스 선택 후 일괄 삭제 기능 구현
- 장바구니 삭제, 상세 페이지 장바구니 담기 기능에 토스트 추가
- 전체 체크박스 선택 상태관리 추가, 수량 변경 시 토스트 추가, 수량 변경 오류 확인 중
resolves #56

♻️ refactor: enhance cart and product detail UX with unified styles, bulk actions, and toast notifications

---

src/app/shop/cart/page.tsx
src/components/features/shopping-cart/CartItemCard.tsx

- 누락된 UI 푸쉬 추가 PR 진행
resolves #186

💄 style: improve UX by refining design, adding bulk delete, and showing toast on cart item delete

---

src/app/live/LiveContent.tsx
src/app/live/LiveData.tsx
src/app/search/searchList.tsx
src/app/shop/ShopList.tsx
src/app/shop/cart/page.tsx
src/app/shop/page.tsx
src/app/shop/purchase/PurchaseClient.tsx
src/components/features/live/LiveCalendar.tsx
src/components/features/shop/ShopCategory.tsx
src/components/features/shop/ShopProduct.tsx
src/components/features/shopping-order/detail/purchase/PaymentSelector.tsx
src/data/actions/orders.ts
src/data/functions/CartFetch.server.ts

- ui 수정
- 라이브 댓글 안 될 경우 대비 문구
- 주문
- 주문 시 장바구니에서 삭제
resolves #212

✨ feat: ordered products delete & ui detail

---

src/data/actions/orders.ts
src/types/cart.ts

- 바로결제 안 되는 이슈 해결
resolves #217

🐛 fix: modify can pay right away

---

src/middleware.ts

- 로그아웃 후 접속 시 → 로그인 화면으로 리다이렉트
- 로그아웃하지 않고 재접속 시 → 토큰 재발급으로 로그인 상태 유지
- 비로그인 상태에서 스플래시, 로그인 외 페이지 접근 시 → 로그인 화면으로 이동
resolves #211

🚨 hotfix: update middleware to enforce login flow and token refresh

---

src/components/features/shop/ProductDetail/ProductDetail.tsx

- ProductActionButtons 컴포넌트의 버튼 border 색상을 수정
- MD PICK 정보 렌더링 로직 수정
- recommendInfo 렌더링 오류 방지
resolves #215

🩹 coolfix: update ProductActionButtons border color, fix MD PICK rendering, and prevent null errors in recommendInfo

---

src/app/not-found.tsx

- 메인 컬러에 맞춰 디자인 수정
- `'use client'` 제거
resolves #222

🩹 coolfix: update design to match primary color

---

src/app/(auth)/login/page.tsx

- 로그인 페이지에 메타데이터 추가
resolves #229

✨ feat: add metadata to login page

---

src/app/shop/orderCompleted/[orderId]/page.tsx
src/app/shop/purchase/PurchaseClient.tsx
src/components/common/LogoutModal.tsx
src/components/features/community/community-comment/CommentListItem.tsx
src/components/features/shopping-order/detail/purchase/PaymentSelector.tsx
src/components/features/shopping-order/detail/purchase/PaymentSummary.tsx
src/components/features/shopping-order/detail/purchase/PurchaseAddress.tsx
src/components/features/shopping-order/detail/purchase/PurchaseProductList.tsx
src/data/actions/orders.ts
src/middleware.ts
src/types/orders.ts

- 총 주문 금액에 따른 포인트 증가 로직 구현
resolves #224

🔀 merge: feature/order/woomin into develop

---

src/app/layout.tsx

🔀 merge: hoxfix/og-graph/woomin into develop

---

src/app/layout.tsx

🔀 merge: hoxfix/oggraph/woomin into develop
